apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
  namespace: devops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      #nodeSelector:
      #  net-type: external
      containers:
      - image: drone/drone:latest
        imagePullPolicy: Always
        name: drone-server
        ports:
        - containerPort: 8000
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
          # Persist our configs in an SQLite DB in here
          - name: drone-server-sqlite-db
            mountPath: /var/lib/drone
        resources:
          requests:
            cpu: 40m
            memory: 32Mi
        env:
        - name: DRONE_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.host
        - name: DRONE_OPEN
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.open
        - name: DRONE_DATABASE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.database.driver
        - name: DRONE_DATABASE_DATASOURCE
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.database.datasource
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: server.secret
        # - name: DRONE_GOGS
        #   valueFrom:
        #     configMapKeyRef:
        #       name: drone-config
        #       key: server.remote.gogs
        # - name: DRONE_GOGS_URL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: drone-config
        #       key: server.remote.gogs.url
        # - name: DRONE_GOGS_PRIVATE_MODE
        #   valueFrom:
        #     configMapKeyRef:
        #       name: drone-config
        #       key: server.remote.gogs.private.mode
        - name: DRONE_GITHUB
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.github
        - name: DRONE_GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.github.client
        - name: DRONE_GITHUB_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.remote.github.secret
        - name: DRONE_LOGS_DEBUG
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: server.debug
      volumes:
        - name: drone-server-sqlite-db
          hostPath:
            path: /rc/data/drone
